### ISSUE TITLE
/deposit endpoint returns 500 when insufficient funds

### ISSUE THREAD

**Issue by ghost** [ConnextProject/rest-api-client#23]
Perhaps a 400 error code would be semantically better. Thoughts?

**Comment by ghost** [comment]
`/hashlock-status/:lockHash/:assetId` also returns 500 when it cannot find the transfer. 404 would be nice.

**Comment by kilrau** [comment]
`/deposit` should calculate needed eth for gas and automatically subtract them from available funds. In this example I have `0.098593` ETH and needed to go through the following procedure to successfully deposit:
```
mainnet > openchannel ETH 0.098593
Error: 2 UNKNOWN: failed to open ETH channel for 9859300: connext server error 500: Internal Server Error
mainnet > openchannel ETH 0.098500
Error: 2 UNKNOWN: failed to open ETH channel for 9850000: connext server error 500: Internal Server Error
mainnet > openchannel ETH 0.098000
Error: 2 UNKNOWN: failed to open ETH channel for 9800000: connext server error 500: Internal Server Error
mainnet > openchannel ETH 0.090000
success
```

This is the log snippet of the connext client when the deposit fails due to insufficient funds:
```
2020-07-28T16:03:31.290Z [DepositController] Deposit started: {"amount":"98593000000000000"}
2020-07-28T16:03:31.290Z [DepositController] Depositing 98593000000000000 of 0x0000000000000000000000000000000000000000 into channel
2020-07-28T16:03:31.299Z [DepositController] requestDepositRights started: {"assetId":"0x0000000000000000000000000000000000000000"}
2020-07-28T16:03:31.299Z [CF-GetAppInstances] Executing with params: {"multisigAddress":"0xE4B2..2e79"}
2020-07-28T16:03:31.302Z [CF-GetAppInstances] Before execution complete in 3 ms
2020-07-28T16:03:31.304Z [CF-GetAppInstances] Executed method implementation in 2 ms
2020-07-28T16:03:31.305Z [CF-RpcRouter] Processed chan_getAppInstances method in 6 ms
2020-07-28T16:03:31.321Z [DepositController] Calling propose install
2020-07-28T16:03:31.321Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0x0000..0000"}
2020-07-28T16:03:31.326Z [CF-GetFreeBalanceState] Before execution complete in 5 ms
2020-07-28T16:03:31.331Z [CF-GetFreeBalanceState] Executed method implementation in 5 ms
2020-07-28T16:03:31.331Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 10 ms
2020-07-28T16:03:31.332Z [CF-ProposeInstall] Executing with params: {"abiEncodings":{"stateEncoding":"tuple( tuple( address to, uint256 amount)[2] transfers, address multisigAddress, address assetId, uint256 startingTotalAmountWithdrawn, uint256 startingMultisigBalance)"},"appDefinition":"0x056c..7cB4","initialState":{"transfers":[{"amount":"0","to":"0xE7Ff..0bcC"},{"amount":"0","to":"0x9a5a..14B7"}],"multisigAddress":"0xE4B2..2e79","assetId":"0x0000..0000","startingTotalAmountWithdrawn":"0","startingMultisigBalance":"149368190000000000"},"initiatorDeposit":"0","initiatorDepositAssetId":"0x0000..0000","multisigAddress":"0xE4B2..2e79","outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","responderIdentifier":"indra7uhB..dggS","responderDeposit":"0","responderDepositAssetId":"0x0000..0000","defaultTimeout":"8640","stateTimeout":"8640"}
2020-07-28T16:03:31.364Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.acquire.0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 request in 32 ms
2020-07-28T16:03:31.365Z [CF-ProposeInstall] Acquired locks 0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 in 34 ms
2020-07-28T16:03:31.368Z [CF-ProposeInstall] Before execution complete in 3 ms
2020-07-28T16:03:31.369Z [CF-ProposeProtocol] [0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79] Initiation started
2020-07-28T16:03:31.386Z [CF-ProposeProtocol] [0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79] Validated proposal 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 17 ms
2020-07-28T16:03:31.395Z [CF-ProposeProtocol] [0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79] Signed set state commitment 0xddb1c1f1fee8b6c10167b2898203ebcb9d5f3857776cc6d090a97c8f60ecdc4a & conditional transfer commitment 0x7c57adf09c71b2d26e21bff38055966971e0c787a416edd0285a8501f5584668 in 2 ms
2020-07-28T16:03:32.985Z [CF-ProposeProtocol] [0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79] Persisted app instance 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 51 ms
2020-07-28T16:03:33.028Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.release.0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 request in 41 ms
2020-07-28T16:03:33.028Z [CF-ProposeInstall] Acquired locks 0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 in 41 ms
2020-07-28T16:03:33.047Z [CF-InstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Response started
2020-07-28T16:03:33.052Z [CF-InstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Validated app 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 5 ms
2020-07-28T16:03:33.059Z [CF-InstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Verified initiator's free balance update sig in 6 ms
2020-07-28T16:03:33.083Z [CF-InstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Persisted app 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 24 ms
2020-07-28T16:03:33.084Z [CF-InstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Response finished in 37 ms
2020-07-28T16:03:33.085Z [ConnextListener] runPostInstallTasks for app DepositApp 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c started
2020-07-28T16:03:33.085Z [ConnextListener] runPostInstallTasks for app DepositApp 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c complete
2020-07-28T16:03:33.085Z [ConnextListener] handleAppProposal for app DepositApp 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c completed
2020-07-28T16:03:33.091Z [CF-RequestHandler] Event for install protocol was processed in 47 ms
2020-07-28T16:03:33.154Z [DepositController] Installed app with id: 0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c
2020-07-28T16:03:33.154Z [DepositController] Successfully obtained deposit rights for 0x0000000000000000000000000000000000000000
2020-07-28T16:03:33.199Z [DepositController] rescindDepositRights started: {"appIdentityHash":"0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c","assetId":"0x0000000000000000000000000000000000000000"}
2020-07-28T16:03:33.200Z [CF-GetAppInstances] Executing with params: {"multisigAddress":"0xE4B2..2e79"}
2020-07-28T16:03:33.206Z [CF-GetAppInstances] Before execution complete in 6 ms
2020-07-28T16:03:33.208Z [CF-GetAppInstances] Executed method implementation in 2 ms
2020-07-28T16:03:33.208Z [CF-RpcRouter] Processed chan_getAppInstances method in 8 ms
2020-07-28T16:03:33.209Z [CF-GetAppInstances] Executing with params: {"multisigAddress":"0xE4B2..2e79"}
2020-07-28T16:03:33.211Z [CF-GetAppInstances] Before execution complete in 2 ms
2020-07-28T16:03:33.213Z [CF-GetAppInstances] Executed method implementation in 2 ms
2020-07-28T16:03:33.214Z [CF-RpcRouter] Processed chan_getAppInstances method in 5 ms
2020-07-28T16:03:33.214Z [CF-Uninstall] Executing with params: {"appIdentityHash":"0x22e2..244c","multisigAddress":"0xE4B2..2e79"}
2020-07-28T16:03:33.259Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.acquire.0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 request in 45 ms
2020-07-28T16:03:33.259Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.acquire.0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c request in 45 ms
2020-07-28T16:03:33.259Z [CF-Uninstall] Acquired locks 0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79,0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 45 ms
2020-07-28T16:03:33.263Z [CF-Uninstall] Before execution complete in 4 ms
2020-07-28T16:03:33.264Z [CF-UninstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Initiation started
2020-07-28T16:03:33.277Z [CF-UninstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Validated uninstall request in 13 ms
2020-07-28T16:03:33.288Z [CF-UninstallProtocol] Computed outcome with current state in 10 ms
2020-07-28T16:03:33.291Z [CF-UninstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] computeStateTransition for uninstall complete in 13 ms
2020-07-28T16:03:33.296Z [CF-UninstallProtocol] [0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c] Signed uninstall commitment initiator in 5 ms
2020-07-28T16:03:33.636Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0x0000..0000"}
2020-07-28T16:03:33.638Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0xdAC1..1ec7"}
2020-07-28T16:03:33.644Z [CF-GetFreeBalanceState] Before execution complete in 8 ms
2020-07-28T16:03:33.647Z [CF-GetFreeBalanceState] Before execution complete in 9 ms
2020-07-28T16:03:33.652Z [CF-GetFreeBalanceState] Executed method implementation in 8 ms
2020-07-28T16:03:33.652Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 16 ms
2020-07-28T16:03:33.653Z [CF-GetFreeBalanceState] Executed method implementation in 6 ms
2020-07-28T16:03:33.653Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 15 ms
2020-07-28T16:03:33.747Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0xdAC1..1ec7"}
2020-07-28T16:03:33.751Z [CF-GetFreeBalanceState] Before execution complete in 4 ms
2020-07-28T16:03:33.754Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0x0000..0000"}
2020-07-28T16:03:33.759Z [CF-GetFreeBalanceState] Executed method implementation in 8 ms
2020-07-28T16:03:33.759Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 12 ms
2020-07-28T16:03:33.767Z [CF-GetFreeBalanceState] Before execution complete in 13 ms
2020-07-28T16:03:33.771Z [CF-GetFreeBalanceState] Executed method implementation in 4 ms
2020-07-28T16:03:33.771Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 17 ms
2020-07-28T16:03:34.726Z [ConnextListener] Received update state event for DepositApp, not doing anything
2020-07-28T16:03:34.769Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.release.0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79 request in 42 ms
2020-07-28T16:03:34.769Z [NodeApiClient] Node responded to indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h.indra7uhB1UYhesBPsbdbPmGw6SZi8pwVvLMDBhSFZyQcZeVi5ydggS.1.lock.release.0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c request in 42 ms
2020-07-28T16:03:34.769Z [CF-Uninstall] Acquired locks 0xE4B24A81dBEaB325c32649d6e5123C2Fb2382e79,0x22e27e052d259c45ee566d8e4d0fdb03b51afbb6e439e880cfb244b13203244c in 42 ms
2020-07-28T16:03:34.770Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0xE4B2..2e79","assetId":"0x0000..0000"}
2020-07-28T16:03:34.776Z [CF-GetFreeBalanceState] Before execution complete in 6 ms
2020-07-28T16:03:34.783Z [CF-GetFreeBalanceState] Executed method implementation in 6 ms
2020-07-28T16:03:34.783Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 13 ms
2020-07-28T16:03:34.783Z [DepositController] rescindDepositRights for assetId 0x0000000000000000000000000000000000000000 complete {"freeBalance":{"0x9a5a06AC25D6b8Ca1f68f87238796a0FfBDc14B7":{"_hex":"0x018d8c75065dc000","_isBigNumber":true},"0xE7Ff258482EaEaFB3aEAc68FF1C7231A723D0bcC":{"_hex":"0x84c22bbad96c00","_isBigNumber":true}}}
[1595952214783] ERROR (70 on connext): Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":62,"error":{"code":-32000,"message":"gas required exceeds allowance (0)"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x13532f7e00\",\"value\":\"0x15e45cfa6571000\",\"from\":\"0xe7ff258482eaeafb3aeac68ff1c7231a723d0bcc\",\"to\":\"0xe4b24a81dbeab325c32649d6e5123c2fb2382e79\"}],\"id\":62,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://192.168.123.44:8545"}, tx={"to":{},"value":{"_hex":"0x015e45cfa6571000","_isBigNumber":true},"from":"0xE7Ff258482EaEaFB3aEAc68FF1C7231A723D0bcC","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /app/node_modules/@ethersproject/abstract-signer/lib/index.js:239:47
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 5)
    Error: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":62,"error":{"code":-32000,"message":"gas required exceeds allowance (0)"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x13532f7e00\",\"value\":\"0x15e45cfa6571000\",\"from\":\"0xe7ff258482eaeafb3aeac68ff1c7231a723d0bcc\",\"to\":\"0xe4b24a81dbeab325c32649d6e5123c2fb2382e79\"}],\"id\":62,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://192.168.123.44:8545"}, tx={"to":{},"value":{"_hex":"0x015e45cfa6571000","_isBigNumber":true},"from":"0xE7Ff258482EaEaFB3aEAc68FF1C7231A723D0bcC","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
        at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
        at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
        at /app/node_modules/@ethersproject/abstract-signer/lib/index.js:239:47
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 5)
        at DepositController.<anonymous> (/app/node_modules/@connext/client/dist/controllers/DepositController.js:61:23)
        at Generator.throw (<anonymous>)
        at rejected (/app/node_modules/@connext/client/dist/controllers/DepositController.js:6:65)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1595952214794] INFO  (70 on connext): request completed
    url: "/deposit"
    statusCode: 500
```

**Comment by kilrau** [comment]
This includes all calls involving amounts , definitely `/deposit` `/hashlock-transfer` and on-chain transfers. Possibly others I can't come up with right now.

**Comment by kilrau** [comment]
Can we bump this one? It's a dependency for quite some UX improvements on our end.
