### ISSUE TITLE
Get/overwrite gas price

### ISSUE THREAD

**Issue by kilrau** [ConnextProject/rest-api-client#93]
- we'd want to query the current gas price that connext will use for the transaction sent by `/onchain-transfer` to allow users to withdraw **all** of their Ether in one transaction
- we'd want to be able to overwrite the gas price of `/onchain-transfer` (it's not exposed in the swagger as of now)

**Comment by kilrau** [comment]
Also battling with this today (my 0.00537 eth were not enough to pay for gas):
```
[1599032692785] ERROR (70 on connext): cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":538,"error":{"code":-32000,"message":"gas required exceeds allowance (11329)"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x6e5c9a0400\",\"from\":\"0x59954c86d21e327baa3fe07aa9b2a06c7c6cb774\",\"to\":\"0xdac17f958d2ee523a2206206994597c13d831ec7\",\"data\":\"0xa9059cbb000000000000000000000000b7984965a22dfe5e2e22aa929027b6e6c85d8a5b0000000000000000000000000000000000000000000000000000000005f5e100\"}],\"id\":538,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://michael1011.at:8545"}, tx={"data":"0xa9059cbb000000000000000000000000b7984965a22dfe5e2e22aa929027b6e6c85d8a5b0000000000000000000000000000000000000000000000000000000005f5e100","to":{},"gasPrice":{"_hex":"0x6e5c9a0400","_isBigNumber":true},"from":"0x59954C86D21e327Baa3Fe07aA9B2A06C7c6cb774","nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
    Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":538,"error":{"code":-32000,"message":"gas required exceeds allowance (11329)"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x6e5c9a0400\",\"from\":\"0x59954c86d21e327baa3fe07aa9b2a06c7c6cb774\",\"to\":\"0xdac17f958d2ee523a2206206994597c13d831ec7\",\"data\":\"0xa9059cbb000000000000000000000000b7984965a22dfe5e2e22aa929027b6e6c85d8a5b0000000000000000000000000000000000000000000000000000000005f5e100\"}],\"id\":538,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://michael1011.at:8545"}, tx={"data":"0xa9059cbb000000000000000000000000b7984965a22dfe5e2e22aa929027b6e6c85d8a5b0000000000000000000000000000000000000000000000000000000005f5e100","to":{},"gasPrice":{"_hex":"0x6e5c9a0400","_isBigNumber":true},"from":"0x59954C86D21e327Baa3Fe07aA9B2A06C7c6cb774","nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
        at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
        at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
        at /app/node_modules/@ethersproject/abstract-signer/lib/index.js:239:47
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 5)
[1599032692793] INFO  (70 on connext): request completed
    url: "/deposit"
    statusCode: 500
    reqId: 236
```
After adding some more eth, it went through fine
